from enum import Enum


class FieldAreaAction(Enum):
    Dummy = 0
    PLACE_UNIT = 1
    ENERGY_BOOST = 2
    DRAW_DECK = 3
    SEARCH_UNIT_CARD = 4
    DESTORY_OPPONENT_FIELD_ENERGY = 5
    REQUIRED_FIRST_PASSIVE_SKILL_PROCESS = 6
    PLAY_ANIMATION = 7
    CHECK_MULTIPLE_UNIT_REQUIRED_FIRST_PASSIVE_SKILL_PROCESS = 8
    TURN_START_FIRST_PASSIVE_SKILL_PROCESS = 9


