from enum import Enum


class MessageNumber(Enum):
    CARD_UNABLE_ATTACK_SUMMON_TURN = 0
    CARD_UNAVAILABLE_USE_SKILL_LACK_ENERGY = 1
    CARD_UNABLE_ATTACK_LACK_ACTION_COUNT = 2
    CARD_UNAVAILABLE_OPPONENT_TURN = 3
    USE_SUPPORT_CARD_ONCE_PER_TURN = 4
    YOUR_TURN = 5
    YOUR_TOMB = 6
    YOUR_LOST_ZONE = 7
    OPPONENT_TURN = 8
    OPPONENT_TOMB = 9
    OPPONENT_LOST_ZONE = 10
    CARD_UNABLE_ATTACK_LACK_ENERGY = 11