from enum import Enum
from enum import Enum


class CustomProtocol(Enum):
    ACCOUNT_REGISTER = 1
    ACCOUNT_LOGIN = 2

    SESSION_LOGIN = 3


    ENTER_MATCHING = 11 #11
    CHECK_MATCHING = 12 #12
    CANCEL_MATCHING = 13 #13
    CHECK_BATTLE_PREPARE = 14 #14
    WHAT_IS_THE_ROOM_NUMBER = 15 #15
    DECK_NAME_LIST = 16 #16
    DECK_CARD_LIST = 17 #17



    ACCOUNT_DECK_REGISTER = 41

    SURRENDER = 4443
    PROGRAM_EXIT = 4444



